name: Build

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 5 * * *"

jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ v1.23, v1.22 ]
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Docker info
        run: docker info
      -
        name: Docker Builder
        run: docker buildx ls
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      -
        name: "ddev ${{ matrix.version }}"
        shell: 'script -q -e -c "bash {0}"'
        run: |
          echo ${{ secrets.GHCR_TOKEN }} | docker login ghcr.io -u ${{ secrets.GHCR_USERNAME }} --password-stdin
          docker buildx create --use --platform=linux/arm64,linux/amd64
          ./build.sh -v ${{ matrix.version }} -p
