name: Test

on:
  pull_request:
  push:
    branches:
      - '**'
      - '!main'
jobs:
  build:
    name: Build Container
    runs-on: ubuntu-latest
    strategy:
      matrix:
        version: [ v1.23, v1.22 ]
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Docker info
        run: docker info
      -
        name: Docker Builder
        run: docker buildx ls
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
      - name: Setup BATS
        uses: mig4/setup-bats@v1
        with:
          bats-version: 1.2.1

      - name: Check out code
        uses: actions/checkout@v1

      - name: "Test ddev ${{ matrix.version }} image"
        shell: 'script -q -e -c "bash {0}"'
        run: |
          ./build.sh -v ${{ matrix.version }} -l
          DDEV_VERSION=${{ matrix.version }} bash bats tests
